--- #YAML:1.0
name:               Net-DNS-Dynamic-Proxyserver
version:            1.1
abstract:           A dynamic DNS proxy server.
author:
    - Marc Sebastian Jakobs
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 1.08
    Moose:                0.92
    Moose::Util::TypeConstraints:  0.92
    Net::DNS:             0.65
    Net::DNS::Nameserver:  749
    Perl6::Junction:      1.4
    POSIX:                1.13
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
